#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"

loc_limit_max=500
loc_limit_soft=300
exclude_file=".githooks/loc-limit-exclude.txt"
check_staged=0
files=()

usage() {
  cat <<'EOF'
Usage: scripts/check-csharp-guidelines.sh [--staged] [file ...]

Checks non-generated C# files for:
- hard LOC limit (> 500 lines fails)
- soft LOC guidance (> 300 lines warns)
- partial type declarations (fails unless excluded)

With --staged, reads staged Git content instead of the working tree.
Without explicit files, checks tracked *.cs files (or staged *.cs files with --staged).
EOF
}

matches_exclusion() {
  local file="$1"

  if [[ ! -f "$exclude_file" ]]; then
    return 1
  fi

  while IFS= read -r pattern || [[ -n "$pattern" ]]; do
    [[ -z "$pattern" ]] && continue
    [[ "$pattern" =~ ^[[:space:]]*# ]] && continue

    pattern="${pattern#"${pattern%%[![:space:]]*}"}"
    pattern="${pattern%"${pattern##*[![:space:]]}"}"
    [[ -z "$pattern" ]] && continue

    if [[ "$file" == $pattern ]]; then
      return 0
    fi
  done < "$exclude_file"

  return 1
}

is_autogenerated() {
  local file="$1"

  case "$file" in
    */obj/*|*/bin/*) return 0 ;;
    *.g.cs|*.designer.cs|*.generated.cs|*.AssemblyInfo.cs) return 0 ;;
  esac

  return 1
}

load_content() {
  local file="$1"

  if [[ "$check_staged" -eq 1 ]]; then
    git show ":$file"
  else
    sed -n '1,$p' -- "$file"
  fi
}

count_lines() {
  local file="$1"
  load_content "$file" | awk 'END { print NR + 0 }'
}

find_partial_declarations() {
  local file="$1"
  load_content "$file" | grep -nE '^[[:space:]]*((public|internal|private|protected|file|sealed|abstract|static|unsafe|readonly|ref|new)[[:space:]]+)*partial[[:space:]]+(class|record|struct|interface)([[:space:]]|$)' || true
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --staged)
      check_staged=1
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      files+=("${1//\\//}")
      ;;
  esac
  shift
done

if [[ "${#files[@]}" -eq 0 ]]; then
  if [[ "$check_staged" -eq 1 ]]; then
    mapfile -t files < <(git diff --cached --name-only --diff-filter=ACMR -- '*.cs')
  else
    mapfile -t files < <(git ls-files -- '*.cs')
  fi
fi

failed=0

for raw_file in "${files[@]}"; do
  file="${raw_file//\\//}"
  [[ -z "$file" ]] && continue
  [[ "$file" == *.cs ]] || continue

  if is_autogenerated "$file"; then
    continue
  fi

  if matches_exclusion "$file"; then
    continue
  fi

  if [[ "$check_staged" -eq 1 ]]; then
    if ! git cat-file -e ":$file" 2>/dev/null; then
      continue
    fi
  elif [[ ! -f "$file" ]]; then
    continue
  fi

  lines="$(count_lines "$file")"
  if [[ "$lines" -gt "$loc_limit_max" ]]; then
    echo "ERROR: $file is $lines lines (max $loc_limit_max). Refactor with composition/helper types or add a justified exclusion in $exclude_file." >&2
    failed=1
  elif [[ "$lines" -gt "$loc_limit_soft" ]]; then
    echo "Warning: $file is $lines lines (recommended <= $loc_limit_soft)." >&2
  fi

  partial_matches="$(find_partial_declarations "$file")"
  if [[ -n "$partial_matches" ]]; then
    echo "ERROR: $file declares a partial type. Use composition or helper classes instead of partials for size management." >&2
    while IFS= read -r match; do
      [[ -z "$match" ]] && continue
      echo "  $match" >&2
    done <<< "$partial_matches"
    echo "  Add a justified exclusion in $exclude_file only when a partial type is genuinely required." >&2
    failed=1
  fi
done

if [[ "$failed" -ne 0 ]]; then
  exit 1
fi
